### ISSUE TITLE
double loadstart event

### ISSUE THREAD

**Issue by sh84** [videojs/videojs-contrib-dash#120]
When video.js switched between the different sources (for example dash->mp4->dash), video element can fired two loadstart event. On second loadstart video.js call dispose and video is not working.

The only thing that I thought to turn off second loadstart handler after dash.manifestloaded event: https://github.com/sh84/videojs-contrib-dash/commit/5f850ef09f4cbedda5e491c13b2d66cc29f4ee62
And this working for me.
Is this correct, maybe exist better way?

**Comment by marguinbc** [comment]
Hi sh84. Thanks for reporting your issue.  The loadstart event should be fired when the player source is initialized or changed. If you are indeed changing the content in the player, this is expected behavior.  

If the dispose call isn't working then that is the actual bug. Can you provide a jsbin sample or sample page that demonstrates the issue?  This will help us better determine the appropriate course of action.

**Comment by sh84** [comment]
Hi marguinbc.

http://jsbin.com/zilipobuzo/edit?html,output
On start it play mp4, push try button and play dash.
Below the button showed player loadstart events.
Press the button again and again have a chance to get an error: loadstart triggered more than 1 time and dash does not play.
Usually 2-3 attempts required to see the problem.

**Comment by forbesjo** [comment]
This is a video.js issue (https://github.com/videojs/video.js/issues/3428) as a workaround please use `player.src(source)` to load your source instead of a source element
