### ISSUE TITLE
.mpd Wrong ?..

### ISSUE THREAD

**Issue by surikat1978** [videojs/videojs-contrib-dash#127]
Hi. Create this    http://195.138.92.130/MV04/DASH/Blondie_dash.xml
what  troubles?
thanks advance!

**Comment by dmlap** [comment]
At first glanceIt looks like you don't have [CORS](http://enable-cors.org/) setup and your mpd is being served with the `application/octet-stream` MIME type instead of `application/xml+dash`. I'd suggest debugging your streams in the [dash.js reference player](http://dashif.org/reference/players/javascript/v2.3.0/samples/dash-if-reference-player/index.html). If you're having trouble playing them back there, you may want to file issues against dash.js (the underlying library that videojs-contrib-dash uses for playback).
