### ISSUE TITLE
Add main configuration to package.json

### ISSUE THREAD

**Issue by chemoish** [videojs/videojs-contrib-dash#17]
I am not exactly sure how dist/ and npm is being managed, but could we add this?

https://docs.npmjs.com/files/package.json#main

```json
{
  "main": "./dist/videojs-dash.min.js"
}
```

**Comment by gkatsev** [comment]
We could. Only issue is that we don't generate a UMD build currently.

**Comment by gkatsev** [comment]
Feel free to submit a PR, though :)

**Comment by chemoish** [comment]
Pardon my noobery. What is UMB build and/or issue?

**Comment by gkatsev** [comment]
UMD: Univeral Module Definition. It allows the packages to work in either node/browserify, AMD, or just plain old-style global javascript.
The issue is that `package.json`'s `main` implies something that could be used in node or at least in a browserify module. Something that you can `require`. However, our build right now only produced the old-style "global" javascript. But it probably still doesn't hurt to have it in there.

**Comment by chemoish** [comment]
Oh, ya its pretty much so I can call `require`, or rather `import` it without having to qualify a path.

This follows the same convention as https://github.com/videojs/video.js/blob/stable/package.json#L22

---

Rant: Though, too bad I can't use either `video.js` or `dashjs` requires due to compilation issues (Have to run debug mode in each).

I'll make a PR.
