### ISSUE TITLE
Issue when changing the track of the video

### ISSUE THREAD

**Issue by mconiglio** [videojs/videojs-contrib-dash#220]
Hello, I'm having the following issue:

When changing the language of the video, it doesn't change the track until new video content is downloaded. So the old language is reproduced for all the part of the video that is already buffered, and when that part finishes, the new language starts being reproduced.

I found some properties that can be passed to Dash.js, but neither of these work:
- [setFastSwitchEnabled](http://cdn.dashjs.org/latest/jsdoc/module-MediaPlayer.html#setFastSwitchEnabled__anchor)
- [setTrackSwitchModeFor](http://cdn.dashjs.org/latest/jsdoc/module-MediaPlayer.html#setTrackSwitchModeFor__anchor)

Am I doing something wrong? Or how can I do to achieve this?

Here is my code ([complete code](http://jsbin.com/yewiseveca/1/edit?html,output)):
```html
<video id="example-video" width="600" height="300" class="video-js vjs-default-skin" controls></video>
<script>
  var player = videojs('example-video', {
    html5: {
      dash: {
        setFastSwitchEnabled: true,
        setTrackSwitchModeFor: ['audio', 'alwaysReplace'],
      }
    }
  });

  player.ready(function() {
    player.src({
      src: 'http://dash.akamaized.net/dash264/TestCases/10a/1/iis_forest_short_poem_multi_lang_480p_single_adapt_aaclc_sidx.mpd',
      type: 'application/dash+xml',
    });

    player.play();
  });
</script>
```

Thanks

**Comment by squarebracket** [comment]
Just to be clear, you're talking about switching _audio_ languages, right?

Taking a look at the [dash.js Github](https://github.com/Dash-Industry-Forum/dash.js/), they have [this ticket](https://github.com/Dash-Industry-Forum/dash.js/issues/2239) still open and [this PR](https://github.com/Dash-Industry-Forum/dash.js/pull/2272) still open which fixes it.

Unfortunately, since their [code freeze started November 29th](https://github.com/Dash-Industry-Forum/dash.js/wiki/Meeting-Minutes#minutes-november-28th-2017) and it still hasn't been merged in, it probably won't be in the next release (2.6.4) but the next-next release (2.6.5). And taking a look at the API, `setFastSwitchEnabled` just says to stick the new segment _closer_ to now, not at now, and `setTrackSwitchModeFor` just applies to the buffer behind the now.

That being said, you can build dash.js with that specific PR applied and load that instead of the regular dash.js. I just tried that and switching audio now happens as soon as you select the language (with a slight buffer, of course).

**Comment by mconiglio** [comment]
Yes, I was talking about audio tracks. I built the dash.js with the code in that PR and it worked. Thanks a lot for your help!

**Comment by squarebracket** [comment]
No problem.

Just as a heads up, in the dash-if slack one of their guys mentioned they were having some issues which were holding up the merge, and they might be splitting that PR into 2. You might want to subscribe to that PR for any updates.

**Comment by mconiglio** [comment]
Oh, thanks for the heads up! I'll subscribe then!
