### ISSUE TITLE
Uncaught You must first call initialize() and set a source before calling this method

### ISSUE THREAD

**Issue by murtaz53** [videojs/videojs-contrib-dash#326]
I am using this plugin with video-js. I have created quality switcher for dash with this. I apply this plugin to videojs player object. I can successfully switch qualities. but when I reload player after then when I am trying to switch quality it throws Uncaught You must first call initialize() and set a source before calling this method. can anyone help me?

I am initialize plugin like this

```
self.player = videojs(id);
self.media_player = self.player.dash.mediaPlayer;
self.media_player.initialize(self.player._id, self.player.src(), true);
```

when I change video quality first time it works successfully.
`self.media_player.setQualityFor('video', quality);`

but when I reload video js player and then try to change quality It throws error Uncaught You must first call initialize() and set a source before calling this method on this line>
`self.media_player.setQualityFor('video', quality);`

`self.media_player.getBitrateInfoListFor('video'); `is working fine. returns quality lists.

what I am doing wrong?

**Comment by murtaz53** [comment]
```
var myPlayer =null;
var media_player =null;
var video_url = "enter_dash_url_here"

var render_video = function () {

    var html = "<video id='video_id' crossorigin='anonymous' class='video-js ow-vjs-player vjs-default-skin vjs-big-play-centered ' height:auto width:auto data-embed='default' controls=''"></video>";

    if (myPlayer) {
        media_player.reset();
        myPlayer.dispose();
    }


    $("body").empty();
    $("body").append(html);

   myPlayer = videojs(video_id, {
                        controlBar: {
                            volumePanel: { inline: false }
                        },
                        html5: {
                            nativeTextTracks: true
                        },
                        autoplay: true
                    });

myPlayer.ready(function () {
var payload = {
                        "src": video_url,
                        "type": "application/dash+xml"
                    };

myPlayer.src(payload);
myPlayer.play();
});

 myPlayer.on('loadedmetadata', function() {

media_player = myPlayer.dash.mediaPlayer;
media_player.initialize($("#" + video_id "), myPlayer.src(), true);   //success
var video_qualities = media_player.getBitrateInfoListFor('video');  //returns successfully
media_player.setQualityFor('video', 0);    //initialize error on second call
                });

}

render_video();     //on first call working, on second call throws error
```

**Comment by murtaz53** [comment]
above is sample code for it.

**Comment by murtaz53** [comment]
@squarebracket : can you help please?

**Comment by squarebracket** [comment]
Some general notes:
1. Pinging me won't make me respond any faster.
2. Please provide code samples with the associated HTML/JS using e.g. https://codepen.io/ (it helps to know what other libraries you're loading).
3. Please format your code, it's very difficult to follow otherwise.

With regards to the content of your issue. Do not do this:
```js
self.media_player.initialize(self.player._id, self.player.src(), true);
```

The call to `initialize` is done by this plugin. DO NOT manage this yourself.

Secondly, be careful with this:
```js
self.media_player = self.player.dash.mediaPlayer;
```

`player.dash.mediaPlayer` is recreated on every source load. So make sure you're not using a stale reference. Accessing `player.dash.mediaPlayer` directly should always use the right one, so maybe try that. If I had to guess, this is where your error is.

I can tell you that this, for instance, will work:
```js
const player = videojs('player');
player.on('loadedmetadata', () => {
  console.log('setting quality');
  player.dash.mediaPlayer.setQualityFor('video', 0);
});
player.src(src1);
player.src(src2);
```

I assume when you say "reload the player", you mean changing sources for the same player. If not, please clarify.

**Comment by murtaz53** [comment]
No In reloading player, I am first destroy player than again initialize src and play.

**Comment by murtaz53** [comment]
Got the solution. thanks for your help @squarebracket.

**Comment by squarebracket** [comment]
You're welcome, glad to hear you've solved the issue.
